### ISSUE TITLE
训练出错

### ISSUE THREAD

**Issue by wang911205** [xialuxi/yolov5-car-plate#13]
Traceback (most recent call last):
  File "train.py", line 552, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 159, in train
    ema.ema.load_state_dict(ckpt['ema'].float().state_dict())
  File "/home/wyw/.conda/envs/py36_torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model:
        size mismatch for model.24.m.0.weight: copying a param with shape torch.Size([42, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([45, 128, 1, 1]).
        size mismatch for model.24.m.0.bias: copying a param with shape torch.Size([42]) from checkpoint, the shape in current model is torch.Size([45]).
        size mismatch for model.24.m.1.weight: copying a param with shape torch.Size([42, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([45, 256, 1, 1]).
        size mismatch for model.24.m.1.bias: copying a param with shape torch.Size([42]) from checkpoint, the shape in current model is torch.Size([45]).
        size mismatch for model.24.m.2.weight: copying a param with shape torch.Size([42, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([45, 512, 1, 1]).
        size mismatch for model.24.m.2.bias: copying a param with shape torch.Size([42]) from checkpoint, the shape in current model is torch.Size([45]).

**Comment by wang911205** [comment]
> Traceback (most recent call last): File "train.py", line 552, in train(hyp, opt, device, tb_writer) File "train.py", line 159, in train ema.ema.load_state_dict(ckpt['ema'].float().state_dict()) File "/home/wyw/.conda/envs/py36_torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict self.**class**.**name**, "\n\t".join(error_msgs))) RuntimeError: Error(s) in loading state_dict for Model: size mismatch for model.24.m.0.weight: copying a param with shape torch.Size([42, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([45, 128, 1, 1]). size mismatch for model.24.m.0.bias: copying a param with shape torch.Size([42]) from checkpoint, the shape in current model is torch.Size([45]). size mismatch for model.24.m.1.weight: copying a param with shape torch.Size([42, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([45, 256, 1, 1]). size mismatch for model.24.m.1.bias: copying a param with shape torch.Size([42]) from checkpoint, the shape in current model is torch.Size([45]). size mismatch for model.24.m.2.weight: copying a param with shape torch.Size([42, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([45, 512, 1, 1]). size mismatch for model.24.m.2.bias: copying a param with shape torch.Size([42]) from checkpoint, the shape in current model is torch.Size([45]).
